services:
  backend:
    # 현재 폴더 기준으로 이미지 빌드
    build:
      context: .
      dockerfile: Dockerfile

    # 컨테이너 이름
    container_name: portfolio-backend

    # 포트 매핑
    ports:
      - "8080:8080"

    # 환경변수 파일 주입
    env_file:
      - .env

    # 컨테이너 환경변수 설정
    environment:
      # 컨테이너 OS 시간대를 KST로 맞춤
      TZ: Asia/Seoul

      # JVM 시간대도 KST로 고정
      JAVA_TOOL_OPTIONS: -Duser.timezone=Asia/Seoul

    # 자동 재시작
    restart: always
