spring.application.name=portfolio-back

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jwt.secret=${JWT_SECRET}

server.forward-headers-strategy=native

# Google OAuth2 client setting
spring.security.oauth2.client.registration.google.client-id=${OAUTH_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${OAUTH_CLIENT_SECRET}

# scope
spring.security.oauth2.client.registration.google.scope=${OAUTH_CLIENT_SCOPE}

# custom properties
spring.front.url=${FRONT_URL}

spring.bus.api.url=${BUS_API_URL}
spring.bus.openapi.key=${BUS_OPENAPI_KEY}